// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	author "alta/project2/features/author"

	mock "github.com/stretchr/testify/mock"
)

// AuthData is an autogenerated mock type for the DataInterface type
type AuthData struct {
	mock.Mock
}

// LoginUser provides a mock function with given fields: email, password
func (_m *AuthData) LoginUser(email string, password string) (author.AuthCore, error) {
	ret := _m.Called(email, password)

	var r0 author.AuthCore
	if rf, ok := ret.Get(0).(func(string, string) author.AuthCore); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(author.AuthCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthData interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthData creates a new instance of AuthData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthData(t mockConstructorTestingTNewAuthData) *AuthData {
	mock := &AuthData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
